title: About Whisper
description: Information about the Whisper app from clickonetwo.io
theme: just-the-docs

url: https://clickonetwo.github.io/whisper

plugins:
  - jekyll-relative-links

mermaid:
  version: 10.3

aux_links:
  ClickOneTwo: 
    - "https://clickonetwo.io"

aux_links_new_tab: true
